# Generated by Django 4.1.2 on 2022-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('clasificacion', models.CharField(max_length=250)),
                ('faccion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
